# Generated by Django 3.1.1 on 2021-10-27 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emobot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
