# Generated by Django 3.2.7 on 2021-10-27 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emobot', '0002_auto_20211027_1857'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='emobot_user',
        ),
    ]
