# Generated by Django 3.2.7 on 2021-10-27 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emobot', '0003_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='webemobot',
        ),
    ]
